  deploy:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t devops-app .

      - name: Run Container
        run: docker run -d -p 3000:3000 devops-app

      - name: Verify Deployment
        run: curl http://localhost:3000 || echo "App not running"

      - name: Run Container Test
        run: docker ps